nav:
  - "index.md"
  - Running cohort queries:
    - Search the public nodes: "public_nodes.md"
    - How to use the query tool: "query_tool.md"
    - Querying the API directly: "api.md"
  - Setting up your own Neurobagel node:
    - Getting started: "getting_started.md"
    - Production deployment: "production_deployment.md"
    - Maintaining a node: "maintaining.md"
    - Deployment with own proxy: "prod_with_own_proxy.md"
  - Annotating your data:
    - Preparing the dataset description: "dataset_description.md"
    - Preparing phenotypic data: "data_prep.md"
    - Annotating phenotypic data: "annotation_tool.md"
    - Preparing imaging data: "preparing_imaging_data.md"
    - Generating harmonized subject-level metadata: "cli.md"
