name: Check markdown links

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: tcort/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        config-file: 'md_link_check_config.json'